apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: digitalocean-cloud-controller-manager
bases:
- ../../../kustomizations/digitalocean-cloud-controller-manager
resources:
- namespace.yaml
generators:
- secret-generator.yaml
